import { StyleSheet } from "react-native";

export default StyleSheet.create({
    container:{
        backgroundColor:'rgb(255,255,255)',
        flex:1
    },
    back_container:{
        flexDirection:"row",
        justifyContent:"space-between",
        alignItems:"center",
        width:"100%",
        position:"absolute"
    },
    back_buttonL:{
        padding:8,
        borderRadius:9999,
        marginLeft:16
    },back_buttonR:{
        padding:8,
        borderRadius:9999,
        marginRight:16
    },
    booking_container:{
        paddingHorizontal:20,
        display:"flex",
        flex:1,
        justifyContent:"space-between",
        backgroundColor:'rgb(255,255,255)',
        paddingTop:32,
        marginTop:-64,
    },
    booking_scroll:{
        marginTop:20,
    },
    booking_div:{
        flexDirection:"row",
        justifyContent:"space-between",
        alignItems:"flex-end",
        marginBottom:10
    },
    booking_title:{
        fontWeight:"700",
        flex:1,
        color:'rgb(64,64,64)',
    },
    booking_price:{
        fontWeight:"600"
    },
    booking_description:{
        color:'rgb(64,64,64)',
        letterSpacing:0.4,
        marginBottom:30,
    },
    info_div:{
        flexDirection:"row",
        justifyContent:"space-between",
        marginHorizontal:4
    },
    info_div2:{
        flexDirection:"row",
        marginLeft:8,
        alignItems:"flex-start"
    },
    info_div3:{
        display:"flex",
        marginTop:8
    },
    info_text:{
        fontWeight:"700",
        color:'rgb(64,64,64)'
    },
    info_text2:{
        color:'rgb(82,82,82)',
        letterSpacing:0.4,
    }
    ,
    booking_button:{
        marginBottom:24,
        marginHorizontal:"auto",
        display:"flex",
        justifyContent:"center",
        alignItems:"center",
        borderRadius:9999,
        alignSelf:"center"
    },
    booking_button_text:{
        color:'rgb(255,255,255)',
        fontWeight:"700"
    }

})